# NumPy Basics
## Foundation for numerical computing and data analysis

## 1. Import NumPy and Environment Check

In [1]:
import numpy as np
import sys

print(f"NumPy version: {np.__version__}")
print(f"Python version: {sys.version}")

NumPy version: 2.5.0
Python version: 3.13.13 (tags/v3.13.13:01104ce, Apr  7 2026, 19:25:48) [MSC v.1944 64 bit (AMD64)]


## 2. Array Creation

In [2]:
# Create array from Python list
arr1 = np.array([1, 2, 3, 4, 5])
print(f"Array from list: {arr1}")
print(f"Shape: {arr1.shape}, dtype: {arr1.dtype}")

# Create 2D array
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
print(f"\n2D Array:\n{arr2d}")
print(f"Shape: {arr2d.shape}")

Array from list: [1 2 3 4 5]
Shape: (5,), dtype: int64

2D Array:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


In [3]:
# Using helper functions
zeros = np.zeros(5)
print(f"Zeros: {zeros}")

ones = np.ones((2, 3))
print(f"\nOnes:\n{ones}")

arange = np.arange(0, 10, 2)
print(f"\nArange(0, 10, 2): {arange}")

linspace = np.linspace(0, 1, 5)
print(f"\nLinspace(0, 1, 5): {linspace}")

eye = np.eye(3)
print(f"\nIdentity matrix:\n{eye}")

Zeros: [0. 0. 0. 0. 0.]

Ones:
[[1. 1. 1.]
 [1. 1. 1.]]

Arange(0, 10, 2): [0 2 4 6 8]

Linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]

Identity matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


## 3. Indexing and Slicing

In [4]:
arr = np.array([10, 20, 30, 40, 50])

# Indexing
print(f"First element: {arr[0]}")
print(f"Last element: {arr[-1]}")

# Slicing
print(f"arr[1:4]: {arr[1:4]}")
print(f"arr[::2]: {arr[::2]}")
print(f"arr[::-1]: {arr[::-1]}")

First element: 10
Last element: 50
arr[1:4]: [20 30 40]
arr[::2]: [10 30 50]
arr[::-1]: [50 40 30 20 10]


In [5]:
# 2D array indexing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"2D Array:\n{arr2d}")

print(f"\nElement at [0, 1]: {arr2d[0, 1]}")
print(f"First row: {arr2d[0, :]}")
print(f"First column: {arr2d[:, 0]}")
print(f"\nSubarray [0:2, 1:3]:\n{arr2d[0:2, 1:3]}")

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Element at [0, 1]: 2
First row: [1 2 3]
First column: [1 4 7]

Subarray [0:2, 1:3]:
[[2 3]
 [5 6]]


In [6]:
# Boolean indexing/masking
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create boolean mask
mask = arr > 5
print(f"Boolean mask (arr > 5): {mask}")
print(f"Elements > 5: {arr[mask]}")

# Fancy indexing
indices = np.array([0, 2, 4])
print(f"\nFancy indexing [0, 2, 4]: {arr[indices]}")

Boolean mask (arr > 5): [False False False False False  True  True  True  True  True]
Elements > 5: [ 6  7  8  9 10]

Fancy indexing [0, 2, 4]: [1 3 5]


## 4. Shape Manipulation

In [7]:
arr = np.arange(12)
print(f"Original array: {arr}")
print(f"Shape: {arr.shape}")

# Reshape
reshaped = arr.reshape(3, 4)
print(f"\nReshaped to (3, 4):\n{reshaped}")

# Transpose
transposed = reshaped.T
print(f"\nTransposed:\n{transposed}")

# Flatten
flattened = reshaped.flatten()
print(f"\nFlattened: {flattened}")

# Ravel (view)
raveled = reshaped.ravel()
print(f"Raveled: {raveled}")

Original array: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Shape: (12,)

Reshaped to (3, 4):
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Transposed:
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]

Flattened: [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled: [ 0  1  2  3  4  5  6  7  8  9 10 11]


## 5. Broadcasting

In [8]:
# Broadcasting examples
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([10, 20, 30])

print(f"Array a (shape {a.shape}):\n{a}")
print(f"\nArray b (shape {b.shape}): {b}")
print(f"\na + b (broadcasting):\n{a + b}")

# Broadcasting with scalar
c = 5
print(f"\na * c (scalar):\n{a * c}")

Array a (shape (2, 3)):
[[1 2 3]
 [4 5 6]]

Array b (shape (3,)): [10 20 30]

a + b (broadcasting):
[[11 22 33]
 [14 25 36]]

a * c (scalar):
[[ 5 10 15]
 [20 25 30]]


## 6. Universal Functions (ufuncs)

In [10]:
arr = np.array([1, 2, 3, 4, 5])

# Arithmetic operations
print(f"Original: {arr}")
print(f"arr + 10: {arr + 10}")
print(f"arr * 2: {arr * 2}")
print(f"arr ** 2: {arr ** 2}")
print(f"np.sqrt(arr): {np.sqrt(arr)}")
print(f"np.exp(arr): {np.exp(arr)}")
print(f"np.log(arr): {np.log(arr)}")

Original: [1 2 3 4 5]
arr + 10: [11 12 13 14 15]
arr * 2: [ 2  4  6  8 10]
arr ** 2: [ 1  4  9 16 25]
np.sqrt(arr): [1.         1.41421356 1.73205081 2.         2.23606798]
np.exp(arr): [  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]
np.log(arr): [0.         0.69314718 1.09861229 1.38629436 1.60943791]


## 7. Aggregations and Reductions

In [12]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(f"Array:\n{arr}")

# Global aggregations
print(f"\nSum: {np.sum(arr)}")
print(f"Mean: {np.mean(arr)}")
print(f"Std: {np.std(arr)}")
print(f"Min: {np.min(arr)}, Max: {np.max(arr)}")

Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum: 45
Mean: 5.0
Std: 2.581988897471611
Min: 1, Max: 9


In [13]:
# Aggregations along axis
print(f"Sum along axis 0 (columns): {np.sum(arr, axis=0)}")
print(f"Sum along axis 1 (rows): {np.sum(arr, axis=1)}")
print(f"\nMean along axis 0: {np.mean(arr, axis=0)}")
print(f"Mean along axis 1: {np.mean(arr, axis=1)}")

# Find indices of extrema
print(f"\nArgmin: {np.argmin(arr)}")
print(f"Argmax: {np.argmax(arr)}")

Sum along axis 0 (columns): [12 15 18]
Sum along axis 1 (rows): [ 6 15 24]

Mean along axis 0: [4. 5. 6.]
Mean along axis 1: [2. 5. 8.]

Argmin: 0
Argmax: 8


## 8. Random Number Generation

In [15]:
# Set seed for reproducibility
np.random.seed(42)

# Random integers
random_ints = np.random.randint(0, 10, size=10)
print(f"Random integers: {random_ints}")

# Random floats
random_floats = np.random.rand(5)
print(f"Random floats: {random_floats}")

# Normal distribution
normal_dist = np.random.randn(5)
print(f"Normal distribution: {normal_dist}")

# Random choice
choice = np.random.choice(['A', 'B', 'C'], size=5)
print(f"Random choice: {choice}")

Random integers: [6 3 7 4 6 9 2 6 7 4]
Random floats: [0.60111501 0.70807258 0.02058449 0.96990985 0.83244264]
Normal distribution: [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]
Random choice: ['A' 'C' 'C' 'C' 'B']


## 9. Performance Comparison

In [16]:
import time

# NumPy vs Python list
size = 1000000

# Python list
py_list = list(range(size))
start = time.time()
py_result = sum(x**2 for x in py_list)
py_time = time.time() - start

# NumPy array
np_array = np.arange(size)
start = time.time()
np_result = np.sum(np_array**2)
np_time = time.time() - start

print(f"Python list time: {py_time:.6f} seconds")
print(f"NumPy array time: {np_time:.6f} seconds")
print(f"NumPy is {py_time/np_time:.1f}x faster")

Python list time: 0.385625 seconds
NumPy array time: 0.019928 seconds
NumPy is 19.4x faster
